src/App.js, src/components/blocks/Header/Header.js, src/components/blocks/Header/Logo/Logo.js
1. Added the dependency instead of the empty array on useEffect
2. Added the image path on variable
=> fix(component/base) - Adding dependency on useEffect

package.json, src/App.js, src/components/blocks/Header/MainMenu/MainMenu.js, src/i18n/config.js, src/i18n/locales/en/translations.json, src/index.js
1. npm install --save react-i18next i18next
2.Create the folders structure under 
src folder 
+-- i18n
+-- locales
|    +-- en
|        +-- translations.json
+-- config.js
3. update config.js file for the necessary  configuration 
Please follow the steps which is mentioned on the below URL :
https://www.freecodecamp.org/news/how-to-add-localization-to-your-react-app/
=> tech(util/base) : add localization

src/App.js
SideBarRight component has been imported as SidebarRight, which caused the build to fail in ubuntu box.
fixes #12
=> ci(build): path import issue 

webpack.config.js
=> tech(webpack): copy styles to public folder upon code build

.github/workflows/main.yml, .gitignore
=> ci(github/actions): add react workflow

src/components/blocks/content/PostItem/PostItem.js, src/components/services/hooks/useGetPostList.js
=> fix(post/api): update endpoint

src/components/blocks/content/PostItem/PostItem.js, src/components/services/hooks/useGetPostList.js
=> fix(post-list/api): fix syntax error

src/static/styles.css
=> fix(searchbar): Update padding in search bar placeholder

src/components/blocks/content/PostItem/PostItem.js, src/components/services/hooks/useGetPostList.js, src/utils/api-endpoints.js, src/utils/axios-instance.js
=> fix(component/postitem): fix max depth exceed error

src/utils/axios-instance.js
=> fix(api/cors): add default cors headers

src/utils/axios-instance.js
Reverts ramsunvtech/linkedin-clone-web#25
=> Revert "fix(api/cors): add default cors headers"

package-lock.json, package.json, src/components/blocks/Header/Logo/Logo.css, src/components/blocks/Header/Logo/Logo.js, src/components/blocks/Header/MainMenu/MainMenu.css, src/components/blocks/Header/MainMenu/MainMenu.js, src/static/styles.css, webpack.config.js
=> tech(webpack): add style-loader and css-loader

PROFILE.md, README.md
Profile readme documentation 
closes #31
=> Profile readme documentation 

package-lock.json, package.json, src/App.js, src/Routes.js, src/modules/Home/Home.js, src/modules/Home/index.js, src/modules/NotFound/NotFound.js, src/modules/NotFound/index.js, src/modules/Profile/Profile.js, src/modules/Profile/index.js, src/utils/route-paths.js, webpack.config.js
**Added react-router**
` npm i react-router --save`
**Added below pages:**
**Home Page**
**Profile Page**
**404 Page**
=> tech(base): add react router

react/src/components/blocks/Header/MainMenu/MainMenu.js, react/src/components/layouts/MainLayout/MainLayout.js, react/src/components/layouts/MainLayout/index.js, react/src/modules/Home/Home.js, react/src/modules/Profile/Profile.js
Created main layout to share on other pages.
=> tech(base/layout): add main layout

react/package.json, react/src/components/blocks/Profile/ExperienceSummaryCard/ExperienceList/ExperienceList.js, react/src/components/blocks/Profile/ExperienceSummaryCard/ExperienceSummaryCard.js, react/src/components/blocks/Profile/ExperienceSummaryCard/ExperienceSummaryCard.module.css, react/src/modules/Profile/Profile.js
=> feat(experience): add icon for add experience

react/package.json, react/src/components/blocks/Profile/ExperienceSummaryCard/AddOrEditExperienceModal/AddOrEditExperienceModal.js, react/src/components/blocks/Profile/ExperienceSummaryCard/AddOrEditExperienceModal/AddOrEditExperienceModal.module.css, react/src/components/blocks/Profile/ExperienceSummaryCard/ExperienceSummaryCard.js, react/src/components/ui/Fields/InputText/InputText.js, react/src/components/ui/Fields/Switch/Switch.js, react/src/components/ui/Fields/Switch/Switch.styles.css, react/src/components/ui/Fields/Switch/index.js, react/src/components/ui/Fields/index.js, react/src/components/ui/Modal/Modal.js, react/src/components/ui/Modal/Modal.module.css, react/src/components/ui/Modal/index.js, react/src/components/ui/index.js
=> feat(experience): add modal form and text field

react/src/components/blocks/Profile/ExperienceSummaryCard/AddOrEditExperienceModal/AddOrEditExperienceModal.js, react/src/components/ui/Fields/Buttons/PrimaryButton/PrimaryButton.js, react/src/components/ui/Fields/Buttons/PrimaryButton/PrimaryButton.module.css, react/src/components/ui/Fields/InputSelectDuration/InputSelectDuration.js, react/src/components/ui/Fields/InputSelectDuration/InputSelectDuration.module.css, react/src/components/ui/Fields/InputSelectDuration/index.js, react/src/components/ui/Fields/Switch/Switch.js, react/src/components/ui/Fields/Switch/Switch.styles.css, react/src/components/ui/Fields/index.js
=> feature(experience): add submit button, start date and end date field

react/src/components/blocks/Profile/ExperienceSummaryCard/AddOrEditExperienceModal/AddOrEditExperienceModal.js, react/src/components/ui/Fields/InputTextarea/InputTextarea.js, react/src/components/ui/Fields/index.js, react/src/components/ui/Modal/Modal.module.css, react/src/components/ui/index.js
=> feature(experience): add style and text area

react/src/components/blocks/Profile/ProfileIntro/ProfileBanner/ProfileBanner.js, react/src/components/blocks/Profile/ProfileIntro/ProfileBanner/ProfileBanner.module.css, react/src/components/blocks/Profile/ProfileIntro/ProfileImage/ProfileImage.js, react/src/components/blocks/Profile/ProfileIntro/ProfileImage/ProfileImage.module.css, react/src/components/blocks/Profile/ProfileIntro/ProfileIntro.js, react/src/components/blocks/Profile/ProfileIntro/ProfileIntro.module.css, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/CompanyAndEducationLinks/CompanyAndEducationLinks.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/CompanyAndEducationLinks/CompanyAndEducationLinks.module.css, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileDetails/ProfileDetails.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileDetails/ProfileDetails.module.css, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileLinks/ProfileLinks.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileLinks/ProfileLinks.module.css, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileSummaryCard.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileSummaryCard.module.css, react/src/components/ui/Cards/SummaryCard/SummaryCard.js, react/src/components/ui/Cards/SummaryCard/SummaryCard.module.css, react/src/components/ui/Fields/Buttons/OutlinedButton/OutlinedButton.js, react/src/components/ui/Fields/Buttons/OutlinedButton/OutlinedButton.module.css, react/src/components/ui/Fields/Buttons/PrimaryButton/PrimaryButton.js, react/src/components/ui/Fields/Buttons/PrimaryButton/PrimaryButton.module.css, react/src/components/ui/Fields/Buttons/SecondaryButton/SecondaryButton.js, react/src/components/ui/Fields/Buttons/SecondaryButton/SecondaryButton.module.css, react/src/components/ui/Icons/AddIcon/AddIcon.js, react/src/components/ui/Icons/AddIcon/AddIcon.module.css, react/src/components/ui/Icons/CameraIcon/CameraIcon.js, react/src/components/ui/Icons/EditIcon/EditIcon.js, react/src/components/ui/Link/Link.js, react/src/components/ui/Link/Link.module.css, react/src/static/images/profile_bg.svg, react/webpack.config.js
=> feat(profile/intro): add profile intro block

react/src/components/blocks/content/PostItem/Header/PostAuthorInfo.js, react/src/components/blocks/content/PostItem/PostItem.js
=> Post Author: Replace Hard Code to Prop Driven

react/src/App.js, react/src/Routes.js, react/src/components/blocks/Header/MainMenu/MainMenu.js, react/src/components/blocks/Profile/ProfileIntro/ProfileBanner/ProfileBanner.js, react/src/components/blocks/Profile/ProfileIntro/ProfileImage/ProfileImage.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileDetails/ProfileDetails.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileLinks/ProfileLinks.js, react/src/components/blocks/Profile/ProfileIntro/ProfileSummaryCard/ProfileSummaryCard.js, react/src/components/layouts/MainLayout/MainLayout.js, react/src/components/ui/Cards/SummaryCard/SummaryCard.js, react/src/modules/Home/Home.js, react/src/modules/NotFound/NotFound.js, react/src/modules/Profile/Profile.js, react/webpack.config.js
=> Tech: Renamed alias from @linkedinWeb to @

react/.babelrc, react/README.md, react/package-lock.json, react/package.json, react/src/index.js
=> Tech: LocatorJS Setup
